### ISSUE TITLE
Unable Start Service on Android 14 (SDK 34)

### ISSUE THREAD

**Issue by MasFha** [Deenu488/CodeAssist-Unofficial#19]
![Screenshot_2024-03-08-00-04-10-36_2870cb4d7e72f8050b62d08052357b72](https://github.com/Deenu488/CodeAssist-Unofficial/assets/140007137/ceea5606-5150-468c-b5d9-adb5624ac3ff)

Build version: 1.0.0 
Build date: 1981-01-01 01:01:02 
Current date: 2024-03-08 00:02:40 
Device: OPPO CPH2461 
 
Stack trace:  
java.lang.RuntimeException: Unable to start service com.tyron.code.service.IndexService@580f1dc with Intent { cmp=com.tyron.code/.service.IndexService }: java.lang.SecurityException: Starting FGS with type systemExempted callerApp=ProcessRecord{4e3f04e 19203:com.tyron.code/u0a1901} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_SYSTEM_EXEMPTED] any of the permissions allOf=false [android.permission.SCHEDULE_EXACT_ALARM, android.permission.USE_EXACT_ALARM, android:activate_vpn] 
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5114)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8821)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.lang.SecurityException: Starting FGS with type systemExempted callerApp=ProcessRecord{4e3f04e 19203:com.tyron.code/u0a1901} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_SYSTEM_EXEMPTED] any of the permissions allOf=false [android.permission.SCHEDULE_EXACT_ALARM, android.permission.USE_EXACT_ALARM, android:activate_vpn] 
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3087)
	at android.os.Parcel.createException(Parcel.java:3071)
	at android.os.Parcel.readException(Parcel.java:3054)
	at android.os.Parcel.readException(Parcel.java:2996)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
	at android.app.Service.startForeground(Service.java:862)
	at com.tyron.code.service.IndexService$$ExternalSyntheticApiModelOutline0.m(D8$$SyntheticClass:0)
	at com.tyron.code.service.IndexService.onStartCommand(IndexService.java:67)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5096)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2700)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2404)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1754)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:14177)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3385)

User actions: 
2024-03-08 00:01:07: MainActivity created
2024-03-08 00:01:07: MainActivity resumed
2024-03-08 00:01:11: MainActivity paused
2024-03-08 00:01:11: SettingsActivity created
2024-03-08 00:01:11: SettingsActivity resumed
2024-03-08 00:01:46: SettingsActivity paused
2024-03-08 00:01:46: MainActivity resumed
2024-03-08 00:01:47: SettingsActivity destroyed

**Comment by Deenu488** [comment]
@MasFha https://github.com/Deenu488/CodeAssist-Unofficial/actions/runs/8193538074

Check this updated code

**Comment by MasFha** [comment]
Build version: 1.0.0 
Build date: 1981-01-01 01:01:02 
Current date: 2024-03-15 01:15:50 
Device: OPPO CPH2461 
 
Stack trace:  
java.lang.RuntimeException: Unable to start service com.tyron.code.service.IndexService@b48241e with Intent { cmp=com.tyron.code/.service.IndexService }: java.lang.SecurityException: Starting FGS with type systemExempted callerApp=ProcessRecord{8dfef34 13184:com.tyron.code/u0a1929} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_SYSTEM_EXEMPTED] any of the permissions allOf=false [android.permission.SCHEDULE_EXACT_ALARM, android.permission.USE_EXACT_ALARM, android:activate_vpn] 
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5114)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2469)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:257)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:8821)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
Caused by: java.lang.SecurityException: Starting FGS with type systemExempted callerApp=ProcessRecord{8dfef34 13184:com.tyron.code/u0a1929} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_SYSTEM_EXEMPTED] any of the permissions allOf=false [android.permission.SCHEDULE_EXACT_ALARM, android.permission.USE_EXACT_ALARM, android:activate_vpn] 
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3087)
	at android.os.Parcel.createException(Parcel.java:3071)
	at android.os.Parcel.readException(Parcel.java:3054)
	at android.os.Parcel.readException(Parcel.java:2996)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
	at android.app.Service.startForeground(Service.java:862)
	at com.tyron.code.service.IndexService.onStartCommand(IndexService.java:67)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5096)
	... 9 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActiveServices.validateForegroundServiceType(ActiveServices.java:2700)
	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2404)
	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1754)
	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:14177)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3385)


User actions:

**Comment by Deenu488** [comment]
I tried to update code for A14 but it didn't work
And also I don't know how to use Index service on A14

**Comment by Deenu488** [comment]
Downgraded to SDK 33
