### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by Rem01Gaming** [Deenu488/CodeAssist-Unofficial#26]
**Describe the bug**
'Create new project' shows empty templates and show error

**To Reproduce**
1. Go to 'Create new project'
2. See empty templates
3. Error will appear

**Expected behavior**
User should see templates for new project as well create a new project.

**Screenshots**
![Screenshot_20240601-182328_CodeAssist](https://github.com/Deenu488/CodeAssist-Unofficial/assets/85148357/60c5c02d-f33f-44ee-9245-f00250466a2b)
![Screenshot_20240601-181516_CodeAssist](https://github.com/Deenu488/CodeAssist-Unofficial/assets/85148357/27f46063-8b88-45c6-a827-aac3f2ff2397)

**Smartphone (please complete the following information):**
 - Device: Realme C25 (RMX3191)
 - OS: DotOS v6.0
 - Version: Android A12L

**Additional context**
Error log:
```Build version: 1.0.0 
Build date: 1981-01-01 01:01:02 
Current date: 2024-06-01 18:23:21 
Device: Realme C25 Series 
 
Stack trace:  
java.lang.IllegalStateException: Fragment WizardFragment{7b199de} (b20d129d-c44d-49b0-b517-f07268f520b8) not attached to a context.
	at androidx.fragment.app.Fragment.requireContext(Fragment.java:969)
	at com.tyron.code.ui.wizard.WizardFragment.extractTemplates(WizardFragment.java:773)
	at com.tyron.code.ui.wizard.WizardFragment.extractTemplatesMaybe(WizardFragment.java:746)
	at com.tyron.code.ui.wizard.WizardFragment.getTemplates(WizardFragment.java:716)
	at com.tyron.code.ui.wizard.WizardFragment.lambda$loadTemplates$11$com-tyron-code-ui-wizard-WizardFragment(WizardFragment.java:690)
	at com.tyron.code.ui.wizard.WizardFragment$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

User actions: 
2024-06-01 18:22:43: MainActivity created
2024-06-01 18:22:43: MainActivity resumed
2024-06-01 18:23:02: MainActivity paused
2024-06-01 18:23:02: SettingsActivity created
2024-06-01 18:23:02: SettingsActivity resumed
2024-06-01 18:23:03: SettingsActivity paused
2024-06-01 18:23:03: MainActivity resumed
2024-06-01 18:23:04: SettingsActivity destroyed
```

**Comment by Deenu488** [comment]
@Rem01Gaming Clear app data and try again

**Comment by Rem01Gaming** [comment]
@Deenu488 Issue still exists after clearing app data.

Is this issue storage related? I'm using Adoptable storage (Format sdcard as internal) feature here, sometimes it also causes issues on other apps.
![Screenshot_20240601-201637_Settings.png](https://github.com/Deenu488/CodeAssist-Unofficial/assets/85148357/74feb9e9-1db1-44ea-986c-70d8c2bff29e)
